# Generated by Django 2.0.7 on 2018-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0003_auto_20180803_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Time',
        ),
        migrations.AlterField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
