# Generated by Django 2.0.7 on 2018-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0004_auto_20180803_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.DateTimeField(default='1950-01-01'),
        ),
    ]
