# Generated by Django 2.0.7 on 2018-08-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0005_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Time',
        ),
    ]
