# Generated by Django 2.0.7 on 2018-08-03 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0006_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
