# Generated by Django 2.0.7 on 2018-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0007_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
