# Generated by Django 2.0.7 on 2018-08-19 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 10, 33, 37, 472411)),
        ),
    ]
