# Generated by Django 2.0.7 on 2018-08-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0010_auto_20180819_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
