# Generated by Django 2.0.7 on 2018-08-20 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0011_auto_20180820_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 10, 50, 31, 435769)),
        ),
    ]
