# Generated by Django 2.0.7 on 2018-08-29 04:25

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PEVA', '0012_auto_20180820_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared_Event',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEVA.Event')),
                ('secondary_user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('PEVA.event',),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 10, 25, 21, 470524)),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
