# Generated by Django 2.0.7 on 2018-08-29 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0013_auto_20180829_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 16, 55, 15, 428261)),
        ),
        migrations.AlterField(
            model_name='shared_event',
            name='secondary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
