# Generated by Django 2.0.7 on 2018-08-30 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEVA', '0016_auto_20180830_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 14, 9, 55, 16160)),
        ),
    ]
